language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install 8.11.2
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails assets:precompile
  - bundle exec rails rspec
  - bundle exec govuk-lint-ruby app config db lib spec --format clang
