version: "3.2"
volumes:
  node_modules:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - "node_modules:/app/node_modules"
    command: bash -c "bundle exec rails server -p 3000 -b '0.0.0.0'"
    environment:
      BASIC_AUTH_USER: 'user'
      BASIC_AUTH_PASSWORD: 'password'
